sticky/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('stickynotes.urls')),
]

stickynotes/forms.py
"""
    name='forms',
    project='ideacloud'
    date='3/13/2020',
    author='Oshodi Kolapo',
"""

from .models import Note
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django_registration.forms import RegistrationFormUniqueEmail


class NoteForm(forms.ModelForm):
    title = forms.CharField(max_length=50, required=True, strip=True)
    description = forms.CharField(required=False)
    is_done = forms.BooleanField(required=False)
    new_dummy = forms.CharField(required=False)

    class Meta:
        model = Note
        fields = ('title', 'description', 'background_color', 'is_done', 'new_dummy')


class NoteForm2(forms.ModelForm):
    title = forms.CharField(max_length=50, required=True, strip=True)

    description = forms.CharField(required=False)

    background_color = forms.CharField(max_length=10, required=True, strip=True)

    is_done = forms.BooleanField(required=False)

    update_delete_dummy = forms.CharField(required=False)

    class Meta:
        model = Note
        fields = ('title', 'description', 'background_color', 'is_done', 'update_delete_dummy')


"""
class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]
"""


class UserRegistrationForm(RegistrationFormUniqueEmail):
    class Meta(RegistrationFormUniqueEmail.Meta):
        model = User
        fields = ["username", "email", "password1", "password2"]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <title>
        {% block title %}Sticky Notes{% endblock title %}
    </title>

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="UTF-8">
    <meta property="og:image" content="{% static 'img/logo-128.png' %}"/>
    <meta property="og:title" content="{% block head_title %}Sticky Notes{% endblock head_title %}"/>
    <meta property="og:description" content="Create colorful todo notes for free"/>
    <meta property="og:image:width" content="265">
    <meta property="og:image:height" content="265">
    <meta property="og:site_name" content="Sticky Notes">
    <meta property="og:site_author" content="Oshodi Kolapo">
    <meta property="og:author" content="Oshodi Kolapo">
    <link rel="icon" href="{% static 'img/favicon.ico' %}" type="image/png">


    <!-- Stylesheets -->
    <link href="{% static 'css/reset.css' %}" type="text/css" rel="stylesheet">
    <link href="{% static 'css/all.css' %}" type="text/css" rel="stylesheet">
    <link href="{% static 'css/bootstrap.css' %}" type="text/css" rel="stylesheet">
    <link href="{% static 'css/stickyNotes.css' %}" type="text/css" rel="stylesheet">
    <link href="{% static 'css/fontawesome.css' %}" type="text/css" rel="stylesheet">
    <link type="text/css" href="{% static 'css/OverlayScrollbars.css' %}" rel="stylesheet"/>
    <link type="text/css" href="{% static 'css/alertify.css' %}" rel="stylesheet"/>
    <link type="text/css" href="{% static 'css/alert-bootstrap.css' %}" rel="stylesheet"/>

</head>
<body>


{% block content %}
    <!-- content -->

{% endblock %}


<footer>
    <div class="container">
        <span>Made With <i class="fas fa-heart">
            </i> by <a href="https://twitter.com/Jayso_o1" target="_blank">SJA</a>
        </span>
    </div>
</footer>


<!-- Javascript files -->
<script src="{% static 'js/jquery.min.js' %}" charset="utf-8"></script>
<script src="{% static 'js/main.js' %}" charset="utf-8"></script>
<script src="{% static 'js/darkmode.js' %}"></script>
<script src="{% static 'js/OverlayScrollbars.js' %}" charset="utf-8"></script>
<script src="{% static 'js/alertify.min.js' %}" charset="utf-8"></script>
<script src="{% static 'js/clipboard.min.js' %}" charset="utf-8"></script>
<script src="{% static 'js/easing.js' %}" charset="utf-8"></script>
<script src="{% static 'js/SmoothScroll.min.js' %}" charset="utf-8"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

<script>
    new Darkmode().showWidget();
</script>

{% include 'partials/_js_utils.html' %}

</body>
</html>

templates/home.html
{% extends "base.html" %}
{% load static %}
{% block content %}

    <div class="header darkmode-ignore" id="header">
        <div class="container">
            <div class="col-md-3 col-sm-5">
                <a href="{% url 'home' %}">
                    <h2>Sticky Notes</h2>
                </a>

{% comment %} logout Button {% endcomment %}
                {% comment %} <div id="wrap" class="container">  {% endcomment %}
                        <div id="bt"   class="col-md-5 col-sm-5">
                            <a href="{% url 'logout' %}" class="btn btn-info btn-lg float-right"  > 
                                <span class="glyphicon glyphicon-log-out">
                                </span>
                            Log out
                            </a>
                        </div>
                        {% comment %} </div> {% endcomment %}
                {% comment %} </div> {% endcomment %}

            </div>


            <div class="col-md-6 col-md-push-3 col-sm-7">
                <div class="hold-img">
                    <img src="{% static 'img/Group 10.svg' %}" alt="">
                </div>
            </div>
        </div>
    </div>


    <div id="notes" class="notes">
        <div class="container">
            <!--Search bar-->
            <div class="searchBar">
                <form action="{% url 'home' %}" id="searchForm">
                    <div class="col-xs-11 nopadding">
                        <input type="text" placeholder="Search Note" name="search_term" value="{{ search_term }}">
                    </div>
                    <div class="col-xs-1 nopadding">
                        <button type="submit" id="searchBtn"><i class="fas fa-search"></i></button>
                    </div>
                </form>
            </div>

            <!-- Check if the request is trying to search or just a normal GET-->
            {% if is_searching %}
                <!--Show all saved notes-->
                <section>
                    <div class="container text-center" style="display: flex; justify-content: center">
                        <div class="col-md-3 col-sm-5">
                            <h2><small>Search results for '{{ search_term }}'</small></h2>
                            <h2><small>Total notes match: {{ notes.count }}</small></h2>
                        </div>
                    </div>
                    {% if notes %}
                        <div id="all-notes" class="all-notes">
                            {% include 'partials/_all_notes.html' %}
                        </div>
                    {% else %}
                        <div class="container text-center"
                            style="display: flex; justify-content: center; margin-bottom: 50px;">
                            <div class="col-md-3 col-sm-5">
                                <h2><small>No note match this search query.</small></h2>
                            </div>
                        </div>
                    {% endif %}
                </section>

            {% else %}
                <!--Request is not for search but a normal GET-->

                <!--Create new note-->
                <div id="noteCreator" class="col-md-4 col-sm-6">

                    <div id="bg" class="single-note add-note white">
                        <form name="createNote" id="createNote" method="POST" data-url="/">
                            {#                        <span class="no-display">{{ form.new_dummy }}</span>#}
                            <input type="hidden" class="d-none" name="new_dummy" id="id_new_dummy">
                            <input class="d-none" type="checkbox" value="False" name="is_done" id="id_is_done">

                            {% csrf_token %}
                            <input name="title" type="text" maxlength="20" placeholder="Type a title ...">
                            <small>Today: {% now "jS F, Y" %}</small>

                            <input class="d-none" name="background_color" value="white"
                                   id="id_background_color">

                            <hr>
                            <textarea name="description" placeholder="Type a description ..."></textarea>
                            <div class="meta">
                                <span id="palette"><i class="fas fa-palette"></i></span>
                                <span>
                                <button class="mark btn btn-lg" type="submit" name="create_btn" id="create_btn">
                                    <i class="fas fa-check"></i>
                                </button>
                            </span>

                            </div>


                            <div id="allColor" class="colors">
                                <div id="circle_blue" class="circle blue">
                                </div>
                                <div id="circle_yellow" class="circle yellow">
                                </div>
                                <div id="circle_red" class="circle red">
                                </div>
                                <div id="circle_purple" class="circle purple">
                                </div>
                                <div id="circle_green" class="circle green">
                                </div>
                                <div id="circle_white" class="circle whiteCircle selected">
                                </div>
                            </div>
                        </form>
                    </div>
                </div>

                <section>
                    <div id="all-notes" class="all-notes">
                        {% include 'partials/_all_notes.html' %}
                    </div>
                </section>
            {% endif %}

        </div>
    </div>
{% endblock %}

templates/register.html
{% extends "base.html" %}

{% block title %}Create an Account{% endblock %}
{% load crispy_forms_tags %}


{% block content %}
    <div class="container text-center"
        style="display: flex; justify-content: center; margin-bottom: 50px; margin-top: 20px">
        <div style="padding: 5px">
            <form method="POST" class="form-group">
                <h2 style="margin: 25px">Create Account</h2>
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-primary">Register</button>
            </form>
        
            <span style="margin-top: 10px">Already have an acount? </span><a
                href="{% url 'login' %}"><span>Log in here</span></a>
        </div>


    </div>
{% endblock %}

templates/shared.html
{% extends "base.html" %}
{% load static %}
{% block content %}

    <div class="header shared-note darkmode-ignore" id="header">
        <div class="container">
            <div class="col-md-3 col-sm-5">
                <a href="{% url 'home' %}"><h2>Shared Note</h2></a>
            </div>
            <div class="col-md-6 col-md-push-3 col-sm-7">
                <div class="hold-img">
                    <img src="{% static 'img/Group 12.svg' %}" alt="">
                </div>
            </div>
        </div>
    </div>

    <div id="notes" class="notes">
        <div class="container">
            <div class="col-md-offset-4 col-sm-offset-2 col-md-4 col-sm-8">
                <div class="single-note shared {{ note.background_color }}">
                    {% if note.is_done %}
                        <h2 class="isDone">{{ note.title }}</h2>
                        <small>Last Updated: {{ note.date_updated|date:"D, dS M Y" }} </small>
                        <hr>
                        <p class="isDone">{{ note.description }}</p>
                    {% else %}
                        <h2>{{ note.title }}</h2>
                        <small>Last Updated: {{ note.date_updated|date:"D, dS M Y" }} </small>
                        <hr>
                        <p>{{ note.description }}</p>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

{% endblock %}